baseurl = "http://example.org"
title = "Hugo Themes - aether"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "../../" 

[params]
brand = "aether"
description = "aether Hugo theme for blogs"
bgimg = "img/ignasi_pattern_s.png"
metaCreator = "Joe Hutchinson"
metaImage = "img/ogimage.jpg"
